[2025-03-26T03:14:22.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T03:14:22.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:10:56.411641+00:00 [queued]>
[2025-03-26T03:14:22.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:10:56.411641+00:00 [queued]>
[2025-03-26T03:14:22.516+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T03:14:22.543+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_into_clickhouse> on 2025-03-26 03:10:56.411641+00:00
[2025-03-26T03:14:22.558+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_clickhouse', 'load_into_clickhouse', 'manual__2025-03-26T03:10:56.411641+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmptc9xcimh']
[2025-03-26T03:14:22.563+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask load_into_clickhouse
[2025-03-26T03:14:22.568+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1258) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T03:14:22.570+0000] {standard_task_runner.py:63} INFO - Started process 1271 to run task
[2025-03-26T03:14:22.653+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:10:56.411641+00:00 [running]> on host 7ea2041f8442
[2025-03-26T03:14:22.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_into_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T03:10:56.411641+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T03:10:56.411641+00:00'
[2025-03-26T03:14:22.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T03:14:22.960+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-03-26T03:15:13.325+0000] {logging_mixin.py:188} INFO - ‚úÖ Downloaded from S3: /tmp/all_college_data.json
[2025-03-26T03:15:13.422+0000] {logging_mixin.py:188} INFO - üîç First 5 rows of data before inserting: [[105899, 'Arizona Christian University', 'Glendale', 'AZ', '1 W. Firestorm Way', 0.7014, 0, 0, 31650, 31650, 6251, 0.7249, 243, 1028, 0.0, 'Private Nonprofit'], [106041, 'Universal Technical Institute of Arizona Inc', 'Avondale', 'AZ', '10695 West Pierce Street', 0.0, 0, 0, 0, 0, 11183, 0.5988, 4763, 1972, 0.0, 'Proprietary'], [106148, 'Yavapai College', 'Prescott', 'AZ', '1100 E Sheldon St', 0.0, 0, 0, 2680, 9340, 6762, 0.0423, 1239, 3577, 0.0, 'Public'], [106245, 'University of Arkansas at Little Rock', 'Little Rock', 'AR', '2801 S University Ave', 0.6146, 21, 1089, 8366, 18957, 14500, 0.381, 1985, 4802, 0.0, 'Public'], [106263, 'University of Arkansas for Medical Sciences', 'Little Rock', 'AR', '4301 W Markham', 0.0, 0, 0, 0, 0, 13000, 0.4806, 200, 1287, 0.0, 'Public']]
[2025-03-26T03:15:13.455+0000] {transform.py:105} ERROR - Error serializing column `peps_ownership` into data type `UInt8`
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/numeric.py", line 30, in _write_column_binary
    column = [int(x) for x in column]
              ^^^^^^
ValueError: invalid literal for int() with base 10: 'Private Nonprofit'
[2025-03-26T03:15:13.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T03:15:13.460+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 159, in load_into_clickhouse
    client.insert("college_data", formatted_data, column_names=column_names)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 635, in insert
    return self.data_insert(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 280, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 472, in _raw_request
    error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 265, in error_handler
    raise ex
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/numeric.py", line 30, in _write_column_binary
    column = [int(x) for x in column]
              ^^^^^^
ValueError: invalid literal for int() with base 10: 'Private Nonprofit'
[2025-03-26T03:15:13.474+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_clickhouse, task_id=load_into_clickhouse, run_id=manual__2025-03-26T03:10:56.411641+00:00, execution_date=20250326T031056, start_date=20250326T031422, end_date=20250326T031513
[2025-03-26T03:15:13.494+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task load_into_clickhouse (invalid literal for int() with base 10: 'Private Nonprofit'; 1271)
[2025-03-26T03:15:13.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-26T03:15:13.532+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T03:15:13.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
