[2025-03-26T03:58:31.276+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T03:58:31.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:53:26.495010+00:00 [queued]>
[2025-03-26T03:58:31.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:53:26.495010+00:00 [queued]>
[2025-03-26T03:58:31.494+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T03:58:31.556+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_into_clickhouse> on 2025-03-26 03:53:26.495010+00:00
[2025-03-26T03:58:31.588+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_clickhouse', 'load_into_clickhouse', 'manual__2025-03-26T03:53:26.495010+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp8qmfyw7g']
[2025-03-26T03:58:31.597+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask load_into_clickhouse
[2025-03-26T03:58:31.604+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1814) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T03:58:31.607+0000] {standard_task_runner.py:63} INFO - Started process 1827 to run task
[2025-03-26T03:58:31.760+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:53:26.495010+00:00 [running]> on host 7ea2041f8442
[2025-03-26T03:58:32.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_into_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T03:53:26.495010+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T03:53:26.495010+00:00'
[2025-03-26T03:58:32.170+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T03:58:32.483+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-03-26T03:58:35.770+0000] {logging_mixin.py:188} INFO - âœ… Downloaded from S3: /tmp/all_college_data.json
[2025-03-26T03:58:35.928+0000] {logging_mixin.py:188} INFO - Renamed Columns: ['latest.admissions.admission_rate.overall', 'latest.admissions.act_scores.50th_percentile.cumulative', 'latest.admissions.sat_scores.average.overall', 'latest.cost.tuition.in_state', 'latest.cost.tuition.out_of_state', 'latest.aid.loan_principal', 'latest.aid.federal_loan_rate', 'latest.completion.4_yr_completion.overall', 'latest.student.size', 'latest.school.peps_ownership', 'latest.student.retention_rate.overall.full_time', 'school.name', 'school.city', 'school.state', 'school.address', 'id']
[2025-03-26T03:58:35.940+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/extract.py:141 FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
[2025-03-26T03:58:35.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T03:58:35.973+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 147, in load_into_clickhouse
    client.insert("college_data", formatted_data, column_names=column_names)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 624, in insert
    context = self.create_insert_context(table,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 741, in create_insert_context
    raise ProgrammingError(f'Unrecognized column {ex} in table {table}') from None
clickhouse_connect.driver.exceptions.ProgrammingError: Unrecognized column 'latest_admissions_admission_rate_overall' in table college_data
[2025-03-26T03:58:35.990+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_clickhouse, task_id=load_into_clickhouse, run_id=manual__2025-03-26T03:53:26.495010+00:00, execution_date=20250326T035326, start_date=20250326T035831, end_date=20250326T035835
[2025-03-26T03:58:36.019+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task load_into_clickhouse (Unrecognized column 'latest_admissions_admission_rate_overall' in table college_data; 1827)
[2025-03-26T03:58:36.047+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-26T03:58:36.075+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T03:58:36.080+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
